<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-EKUOLJ2" name="com.revature.controllertests.ModuleControllerTest" tests="4" failures="1" timestamp="17 Sep 2019 13:42:03 GMT" time="0.016" errors="0">
  <testcase name="deleteModule" time="0.003" classname="com.revature.controllertests.ModuleControllerTest"/>
  <testcase name="getAllModules" time="0.007" classname="com.revature.controllertests.ModuleControllerTest">
    <failure type="java.lang.AssertionError" message="Failed to get back modules expected [[{&quot;id&quot;:1,&quot;subject&quot;:&quot;subject&quot;,&quot;created&quot;:1,&quot;links&quot;:[{&quot;id&quot;:1,&quot;contentId&quot;:1,&quot;moduleId&quot;:1,&quot;affiliation&quot;:&quot;affiliation&quot;}]}]] but found [[{&quot;id&quot;:1,&quot;subject&quot;:&quot;subject&quot;,&quot;created&quot;:1,&quot;links&quot;:[{&quot;id&quot;:1,&quot;contentId&quot;:1,&quot;moduleId&quot;:1,&quot;affiliation&quot;:&quot;affiliation&quot;}],&quot;parentModules&quot;:null,&quot;childrenModules&quot;:null}]]">
      <![CDATA[java.lang.AssertionError: Failed to get back modules expected [[{"id":1,"subject":"subject","created":1,"links":[{"id":1,"contentId":1,"moduleId":1,"affiliation":"affiliation"}]}]] but found [[{"id":1,"subject":"subject","created":1,"links":[{"id":1,"contentId":1,"moduleId":1,"affiliation":"affiliation"}],"parentModules":null,"childrenModules":null}]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.revature.controllertests.ModuleControllerTest.getAllModules(ModuleControllerTest.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getAllModules -->
  <testcase name="givenValidDataCreateModule" time="0.004" classname="com.revature.controllertests.ModuleControllerTest"/>
  <testcase name="getModuleById" time="0.002" classname="com.revature.controllertests.ModuleControllerTest"/>
</testsuite> <!-- com.revature.controllertests.ModuleControllerTest -->
